---
registry:
  - type: dockerhub
    name: docker
    url: https://registry.hub.docker.com
    user: DOCKERHUB_USER
    pass: DOCKERHUB_PASS
    org: DOCKERHUB_ORG
    fail_on_error: false
  - type: rhcc
    name: rhcc
    url: registry.access.stage.redhat.com
    fail_on_error: true
    whitelist: 
      - "^legitimate.*-apb$"    
    blacklist: 
      - "malicious.*-apb$"
      - "^specific-blacklist-apb$"
dao:
  etcd_host: localhost
  etcd_port: 2379
log:
  logfile: /var/log/ansible-service-broker/asb.log
  stdout: true
  level: debug
  color: true
openshift:
  host: ""
  ca_file: ""
  bearer_token_file: ""
  image_pull_policy: IfNotPresent
broker:
  bootstrap_on_startup: true
  dev_broker: true
  launch_apb_on_bind: false
  recovery: true
  output_request: true
  auth:
    type: basic
    enable: true
